spring:
  datasource:
    url: jdbc:mysql://192.168.3.10:3306/example?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: guokai
mybatis:
  mapperLocations: classpath:/mapper/*.xml
server:
  port: 8080
